fix: add check for jq

diff --git a/yarn-run b/yarn-run
--- a/yarn-run
+++ b/yarn-run
@@ -12,6 +12,11 @@ if ! command -v fzf >/dev/null 2>&1; then
   exit 1
 fi
 
+if ! command -v jq >/dev/null 2>&1; then
+  echo "jq not found"
+  exit 1
+fi
+
 if [ ! -f package.json ]; then
   echo "No package.json found"
   exit 1
